// // File generated by flutterfire_cli.
// // ignore_for_file: type=lint
// import 'dart:io';
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
//
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (identical(defaultTargetPlatform, TargetPlatform.android)) {
//       return android;
//     }
//     if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
//       return ios;
//     }
//     if (identical(defaultTargetPlatform, TargetPlatform.web)) {
//       return web;
//     }
//     throw UnsupportedError(
//       'DefaultFirebaseOptions are not supported for this platform.',
//     );
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
//     appId: '1:123456789012:android:abcdefghijklmnopqrst',
//     messagingSenderId: '123456789012',
//     projectId: 'green-route-app',
//     databaseURL:
//         'https://green-route-app-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'green-route-app.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
//     appId: '1:123456789012:ios:abcdefghijklmnopqrst',
//     messagingSenderId: '123456789012',
//     projectId: 'green-route-app',
//     databaseURL:
//         'https://green-route-app-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'green-route-app.appspot.com',
//     iosBundleId: 'com.example.greenRouteApp',
//   );
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
//     appId: '1:123456789012:web:abcdefghijklmnopqrst',
//     messagingSenderId: '123456789012',
//     projectId: 'green-route-app',
//     authDomain: 'green-route-app.firebaseapp.com',
//     databaseURL:
//         'https://green-route-app-default-rtdb.asia-southeast1.firebasedatabase.app',
//     storageBucket: 'green-route-app.appspot.com',
//   );
// }
//
// TargetPlatform get defaultTargetPlatform {
//   if (Platform.isAndroid) return TargetPlatform.android;
//   if (Platform.isIOS) return TargetPlatform.iOS;
//   if (Platform.isWindows) return TargetPlatform.windows;
//   if (Platform.isMacOS) return TargetPlatform.macOS;
//   if (Platform.isLinux) return TargetPlatform.linux;
//   throw UnsupportedError('Unknown platform');
// }
//
// enum TargetPlatform { android, iOS, windows, macOS, linux, web }
